# Generated by Django 4.2.2 on 2023-06-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaCompras', '0002_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
