# Generated by Django 4.2.2 on 2023-06-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaCompras', '0005_carrito_delete_productohome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
