# Generated by Django 4.2.2 on 2023-06-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaCompras', '0008_registrocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
